server:
  contextPath: null
spring:
  jackson:
    serialization:
      INDENT_OUTPUT: true
  jpa:
    show-sql: false
    generate-ddl: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        ddl-auto: create-drop
      
  datasource:
    url: jdbc:mysql://localhost:3306/webboot
    username: root
    password: CocoRosie87
    driver-class-name: com.mysql.jdbc.Driver
jwt:
  header: Authorization
  secret: mySecret
  expiration: 604800
  route:
    authentication:
      path: auth
      refresh: refresh