# config context path to "/" by setting an empty string
server:
  contextPath:

# JACKSON
spring:
  jackson:
    serialization:
      INDENT_OUTPUT: true

  datasource:
    url: jdbc:mysql://localhost:3306/webboot
    driverClassName: com.mysql.jdbc.Driver
    username: root
    password: Grammar1066

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update

jwt:
  header: Authorization
  secret: mySecret
  expiration: 604800
  route:
    authentication:
      path: auth
      refresh: refresh

logging:
  level:
    org.hibernate.sql: debug
    org.hibernate.type.descriptor.sql: trace
    

#logging:
#  level:
#    org.springframework:
#      security: DEBUG